CREATE OR REPLACE WAREHOUSE WH_INVENTORY
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

CREATE OR REPLACE DATABASE INVENTORY_A4G;

USE DATABASE inventory_a4g;
USE SCHEMA PUBLIC;


USE WAREHOUSE WH_INVENTORY;
USE DATABASE INVENTORY_A4G;
USE SCHEMA public;

SELECT CURRENT_WAREHOUSE(), CURRENT_DATABASE(), CURRENT_SCHEMA();
