show roles;

GRANT USAGE
ON DATABASE inventory_a4g
TO ROLE role_inventory_a4g;

GRANT USAGE
ON SCHEMA DEMO_DB.PUBLIC
TO ROLE STUDENT_ROLE;

GRANT CREATE TABLE, CREATE VIEW, CREATE DYNAMIC TABLE
ON SCHEMA inventory_a4g.public
TO ROLE role_inventory_a4g;

GRANT USAGE
ON WAREHOUSE WH_INVENTORY
TO ROLE role_inventory_a4g;

CREATE OR REPLACE VIEW V_LATEST_STOCK AS
SELECT *
FROM RAW_DAILY_STOCK
QUALIFY ROW_NUMBER() OVER (PARTITION BY location, item ORDER BY stock_date DESC) = 1;

SELECT * FROM V_LATEST_STOCK;
